### ISSUE TITLE
when will the full code be open-sourced approximately

### ISSUE THREAD

**Issue by lth456321** [WenbingWei/IIFC-Net#1]
Hello researchers:
I'm very interested about your work and want to know more about the training detail, so I want to ask when will the full code be open-sourced approximately
Thank you

**Comment by wen0320** [comment]
Hi.&nbsp;

Thank you for your interest in my article. I have been so busy preparing for my graduation thesis recently that I didn't have time to sort out the code.&nbsp;

However, you can feed IIFC-Net into the MP-Net framework for training, just modify the MP-Net training loss.&nbsp;

The result of IIFC-Net removing phase loss training on MP-SENet framework is: PESQ: 3.41.

The MP-SENet code is available at https://github.com/yxlu-0102/MP-SENet





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WenbingWei/IIFC-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月8日(星期五) 晚上8:55
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[WenbingWei/IIFC-Net] when will the full code be open-sourced approximately (Issue #1)





 
Hello researchers:
 I'm very interested about your work and want to know more about the training detail, so I want to ask when will the full code be open-sourced approximately
 Thank you

**Comment by lth456321** [comment]
Thanks for your reply. Do you mean I can replace the generator of MP-SENet with IIFC-Net and delete the phase loss, then I can get a Network with PESQ=3.41? Otherwise, I find the segmentation size of MP-SENet is 2s which is different from your article's 4s, do you think the difference will affect the training?
Thank you

**Comment by wen0320** [comment]
Replacing MP-SENet's generator with IIFC-Net and removing the phase loss results in a network with PESQ=3.41. That's OK. Thank you for reminding me that 4s should be used to train IIFC-Net. Because I found that 4s training results are better than 2s.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WenbingWei/IIFC-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月12日(星期二) 中午11:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WenbingWei/IIFC-Net] when will the full code be open-sourced approximately (Issue #1)





 
Thanks for your reply. Do you mean I can replace the generator of MP-SENet with IIFC-Net and delete the phase loss, then I can get a Network with PESQ=3.41? Otherwise, I find the segmentation size of MP-SENet is 2s which is different from your article's 4s, do you think the difference will affect the training?
 Thank you

**Comment by lth456321** [comment]
Is the segmentation method you use the same as the MP-SENET? Most Speech in VCTK has a duration of less than 4s, I think the segmentation method of MP-SENET will cause a lot of blank frames, or you reorganize the voice into 4s beforehand. Otherwise, the FFT number of your article 512 is different from MP-SENET's 400, do you think it will affect the training?
Thank you

**Comment by wen0320** [comment]
The segmentation method we use is similar to MP-SENet. As you mentioned, some of the speech in the VCTK dataset is less than 4 seconds. Before segmentation, we will extend the speech length to be greater than or equal to 4 seconds (padding with zeros if less than 4 seconds). Although this may result in many silent frames, the impact on PESQ will not be significant (0.01~0.03). We have analyzed the speech in VCTK, and approximately 70% of the speech length exceeds 4 seconds. Additionally, using the parameters set in MP-SENet for STFT will not affect the training of IIFC-Net.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WenbingWei/IIFC-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月12日(星期二) 中午12:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WenbingWei/IIFC-Net] when will the full code be open-sourced approximately (Issue #1)





 
Is the segmentation method you use the same as the MP-SENET? Most Speech in VCTK has a duration of less than 4s, I think the segmentation method of MP-SENET will cause a lot of blank frames, or you reorganize the voice into 4s beforehand. Otherwise, the FFT number of your article 512 is different from MP-SENET's 400, do you think it will affect the training?
 Thank you

**Comment by lth456321** [comment]
We sorted the VCTK dataset by duration and found that only about 11% of the speech duration was greater than or equal to 4 seconds. Did I use the wrong dataset or misunderstand your meaning?
Thank you
![19acdcc1e83160b2c4c02b1088a6f80](https://github.com/WenbingWei/IIFC-Net/assets/117817587/f92e0fa6-e740-40d7-8adc-563da135a6bc)
![bbd04719c8bfd88816faf436ddb266a](https://github.com/WenbingWei/IIFC-Net/assets/117817587/a7c74108-10cf-4509-a3be-03defd6797b0)
